### ISSUE TITLE
Props in the first execution of popup.html or content-script.

### ISSUE THREAD

**Issue by nikosgi** [tshaddix/react-chrome-redux-examples#11]
It appears that every time I pop the popup.html or when the content-script runs for the first time in a tab, the function :
```javascript
const mapStateToProps = (state) => {
  return {
    count: state.count
  };
};
```
executes 2 times. The first time, the props ( 'count' in this example) passes as undefined to the render function
```javascript
  render() {
    console.log(this.props.count);
    return (
      <div>
        Count: {this.props.count}
      </div>
    );
  }
```
, and the second time it passes the normal value stored in the state. 

Any idea what causes this issue?

**Comment by vhmth** [comment]
You figure this out @nikosgi?

**Comment by nikosgi** [comment]
@vhmth 

Yes, the reason behind it was in the index.js of the popup. In this example the proxyStore doesn't get the initial state from the store in the background page before it renders. However, the basic usage of react-chrome-redux mentions that you should wait for the store to connect to the background page, and then render the app.

```javascript

proxyStore.ready().then( ()=> {

render(
    <Provider store={proxyStore}>
    	<App/>
    </Provider>
  , document.getElementById('app'));

});


```

**Comment by vhmth** [comment]
Ahhh 👍. Yeah the store needs time to connect to the bg. Glad you figured it out!
