### ISSUE TITLE
Where do i inject scripts into the page?

### ISSUE THREAD

**Issue by jp3492** [tshaddix/react-chrome-redux-examples#14]
I am working with the clicker-key example and i want to figure out how to inject a script that reads the youtube player current time and sends it per message to my redux store.
Im trying so many things but i somehow have issues injecting scripts into the body of the page.
The only way it seems to work is like this:

const script = document.createElement('script');
script.type = "text/javascript";
script.text = "const player = document.getElementById('movie_player'); console.log(player.getCurrentTime());";
document.body.insertBefore(script, document.body.childNodes[0]);

Every other approach, either gives me an "getCurrentTime() is not a function", or "is not a valid DOM element", or issues with importing the React module.

Any suggestions for a proper solution to get the curretn youtube player time on a click event with sendMessage from the popup interface?

Would help me a lot, been batteling myelf with this problem for days.
Thanks a lot

**Comment by jp3492** [comment]
it seems very impractical to write the script code as a string

**Comment by vhmth** [comment]
@jp3492 this is not a `react-chrome-redux` issue. Please have a look at `chrome.tabs.executeScript`:

https://developer.chrome.com/extensions/tabs

Also, you can define your content script in your manifest file and even scope content scripts to specific tab URLs:

https://developer.chrome.com/extensions/content_scripts

The content script is the defacto way of implementing scripts that get injected into web pages. Let me know if that helps.
