### ISSUE TITLE
babel-register not loading

### ISSUE THREAD

**Issue by faisal64** [tshaddix/react-chrome-redux-examples#15]
After I download the project. installed all the dependencies and run the project it shows babel-register not loading error. still it runs but I can't use spread operator. wherever I use spread operator application crashes. I need help please.

**Comment by tshaddix** [comment]
Closing for now. Please let me know if this is still an issue.

**Comment by faisal64** [comment]
No man. That is still not working. it shows the error.
[image: Screenshot at Feb 18 02-44-29.png]

**Comment by tshaddix** [comment]
Hey @faisal64  - I'm not seeing the image come through on the issues. Do you mind adding directly to github thread? https://github.com/tshaddix/react-chrome-redux-examples/issues/15

**Comment by tshaddix** [comment]
Also, have you updated your babelrc? https://stackoverflow.com/questions/49301610/babel-node-doesnt-transform-spread-operator-on-preset-env

The babel setups in these examples are really old and bare-minimum.

**Comment by faisal64** [comment]
![screenshot at feb 18 02-44-29](https://user-images.githubusercontent.com/32549955/52919072-926f8000-3328-11e9-8f43-084c26a1079a.png)

**Comment by faisal64** [comment]
Can you please update the project?

**Comment by tshaddix** [comment]
It's really difficult to help with this because it's working fine for myself and others with a clean install.

Also, just to be clear, this is an example project and should not be used as as a template or bootstrapping project. This is just for reference.

**Comment by faisal64** [comment]
The problem is solved. I updated all the packages and that error is not showing anymore. Huge thanks to you @tshaddix.

**Comment by tshaddix** [comment]
Thrilled to hear that! Take care @faisal64 !
