### ISSUE TITLE
Development environment

### ISSUE THREAD

**Issue by alfonsoperez** [tshaddix/react-chrome-redux-examples#3]
This is more a question than an issue, I would like to know what would be the development setup for these examples, I tried using [boiler plates like this](https://github.com/jhen0409/react-chrome-extension-boilerplate) but it's all too convoluted for my use case.

Ideas?.

Thanks

**Comment by tshaddix** [comment]
Hey there @alfonsoperez . You could just copy any of the top level directories in this project and be on your way.

https://github.com/tshaddix/react-chrome-redux-examples/tree/master/clicker

This one is pretty empty and has all the build stuff setup. Would that work for you?

**Comment by alfonsoperez** [comment]
Hey @tshaddix, thanks for the reply, but my question was more in the sense of, do you develop, then build and reload the extension every time to test it?.

Thanks

**Comment by tshaddix** [comment]
@alfonsoperez I do have to reload every time. It's a bummer, I know.

**Comment by alfonsoperez** [comment]
Ok, thanks!
