### ISSUE TITLE
package.json should be updated with latest packages 

### ISSUE THREAD

**Issue by AgrimPrasad** [tshaddix/react-chrome-redux-examples#4]
I based my project off of this boilerplate, but was stuck for several hours due to the packages in package.json being quite old. They should be updated, and the code should be updated to go along with it. 

I'll probably work on this myself in the next few days if I have time.

**Comment by tshaddix** [comment]
Hey @AgrimPrasad! I know it's been awhile since this issue was created. Do you know if this was fixed with the changes in #7?

**Comment by AgrimPrasad** [comment]
Yup, this should be fixed with #7 Thanks for following up.

**Comment by tshaddix** [comment]
@AgrimPrasad Awesome!
