### ISSUE TITLE
[Question] how can i use flow type checking with the example, i tried but not success to make webpack build correctly. btw thank for awesome project

### ISSUE THREAD

**Issue by hunght** [tshaddix/react-chrome-redux-examples#8]

**Comment by tshaddix** [comment]
Hi @hunght .  You're quite welcome!

The examples have not been setup with Flow, but it is definitely possible. Without seeing your code, it's a little hard to debug what's going on.

Here is an example using `react-chrome-redux` and `flow` with `webpack`: https://github.com/tshaddix/next-read/tree/v-friendly
